export type NpsUnitType = 'park' | 'monument';

export interface NpsUnit {
  name: string;
  type: NpsUnitType;
}

export const NPS_UNITS = [
  // National Parks (63)
  { name: 'Acadia', type: 'park' },
  { name: 'American Samoa', type: 'park' },
  { name: 'Arches', type: 'park' },
  { name: 'Badlands', type: 'park' },
  { name: 'Big Bend', type: 'park' },
  { name: 'Biscayne', type: 'park' },
  { name: 'Black Canyon of the Gunnison', type: 'park' },
  { name: 'Bryce Canyon', type: 'park' },
  { name: 'Canyonlands', type: 'park' },
  { name: 'Capitol Reef', type: 'park' },
  { name: 'Carlsbad Caverns', type: 'park' },
  { name: 'Channel Islands', type: 'park' },
  { name: 'Congaree', type: 'park' },
  { name: 'Crater Lake', type: 'park' },
  { name: 'Cuyahoga Valley', type: 'park' },
  { name: 'Death Valley', type: 'park' },
  { name: 'Denali', type: 'park' },
  { name: 'Dry Tortugas', type: 'park' },
  { name: 'Everglades', type: 'park' },
  { name: 'Gates of the Arctic', type: 'park' },
  { name: 'Gateway Arch', type: 'park' },
  { name: 'Glacier', type: 'park' },
  { name: 'Glacier Bay', type: 'park' },
  { name: 'Grand Canyon', type: 'park' },
  { name: 'Grand Teton', type: 'park' },
  { name: 'Great Basin', type: 'park' },
  { name: 'Great Sand Dunes', type: 'park' },
  { name: 'Great Smoky Mountains', type: 'park' },
  { name: 'Guadalupe Mountains', type: 'park' },
  { name: 'Haleakalā', type: 'park' },
  { name: 'Hawaiʻi Volcanoes', type: 'park' },
  { name: 'Hot Springs', type: 'park' },
  { name: 'Indiana Dunes', type: 'park' },
  { name: 'Isle Royale', type: 'park' },
  { name: 'Joshua Tree', type: 'park' },
  { name: 'Katmai', type: 'park' },
  { name: 'Kenai Fjords', type: 'park' },
  { name: 'Kings Canyon', type: 'park' },
  { name: 'Kobuk Valley', type: 'park' },
  { name: 'Lake Clark', type: 'park' },
  { name: 'Lassen Volcanic', type: 'park' },
  { name: 'Mammoth Cave', type: 'park' },
  { name: 'Mesa Verde', type: 'park' },
  { name: 'Mount Rainier', type: 'park' },
  { name: 'New River Gorge', type: 'park' },
  { name: 'North Cascades', type: 'park' },
  { name: 'Olympic', type: 'park' },
  { name: 'Petrified Forest', type: 'park' },
  { name: 'Pinnacles', type: 'park' },
  { name: 'Redwood', type: 'park' },
  { name: 'Rocky Mountain', type: 'park' },
  { name: 'Saguaro', type: 'park' },
  { name: 'Sequoia', type: 'park' },
  { name: 'Shenandoah', type: 'park' },
  { name: 'Theodore Roosevelt', type: 'park' },
  { name: 'Virgin Islands', type: 'park' },
  { name: 'Voyageurs', type: 'park' },
  { name: 'White Sands', type: 'park' },
  { name: 'Wind Cave', type: 'park' },
  { name: 'Wrangell–St. Elias', type: 'park' },
  { name: 'Yellowstone', type: 'park' },
  { name: 'Yosemite', type: 'park' },
  { name: 'Zion', type: 'park' },
  // National Monuments (selected major units)
  { name: 'Aztec Ruins', type: 'monument' },
  { name: 'Bears Ears', type: 'monument' },
  { name: 'Buck Island Reef', type: 'monument' },
  { name: 'Canyon de Chelly', type: 'monument' },
  { name: 'Capulin Volcano', type: 'monument' },
  { name: 'Casa Grande Ruins', type: 'monument' },
  { name: 'Castillo de San Marcos', type: 'monument' },
  { name: 'Cedar Breaks', type: 'monument' },
  { name: 'Chaco Culture', type: 'monument' },
  { name: 'Colorado', type: 'monument' },
  { name: 'Craters of the Moon', type: 'monument' },
  { name: 'Devils Postpile', type: 'monument' },
  { name: 'Devils Tower', type: 'monument' },
  { name: 'Dinosaur', type: 'monument' },
  { name: 'El Malpais', type: 'monument' },
  { name: 'El Morro', type: 'monument' },
  { name: 'Florissant Fossil Beds', type: 'monument' },
  { name: 'Fort Sumter', type: 'monument' },
  { name: 'George Washington Birthplace', type: 'monument' },
  { name: 'Grand Staircase–Escalante', type: 'monument' },
  { name: 'Hovenweep', type: 'monument' },
  { name: 'Jewel Cave', type: 'monument' },
  { name: 'John Day Fossil Beds', type: 'monument' },
  { name: 'Lava Beds', type: 'monument' },
  { name: 'Montezuma Castle', type: 'monument' },
  { name: 'Muir Woods', type: 'monument' },
  { name: 'Natural Bridges', type: 'monument' },
  { name: 'Navajo', type: 'monument' },
  { name: 'Ocmulgee Mounds', type: 'monument' },
  { name: 'Oregon Caves', type: 'monument' },
  { name: 'Organ Pipe Cactus', type: 'monument' },
  { name: 'Rainbow Bridge', type: 'monument' },
  { name: 'Scotts Bluff', type: 'monument' },
  { name: 'Statue of Liberty', type: 'monument' },
  { name: 'Sunset Crater Volcano', type: 'monument' },
  { name: 'Timpanogos Cave', type: 'monument' },
  { name: 'Tonto', type: 'monument' },
  { name: 'Walnut Canyon', type: 'monument' },
  { name: 'Wupatki', type: 'monument' },
  { name: 'Yucca House', type: 'monument' },
].sort((a, b) => a.name.localeCompare(b.name)) as NpsUnit[];

export const NPS_NAMES = NPS_UNITS.map((u) => u.name);
